- name:             Ethereum Deposit Wallet
  blockchain_key:   eth-rinkeby
  currency_id:      eth
  address:          '0xc3f1a871ad14dcf255e27767241b869e7a878dd3'
  kind:             deposit
  nsig:             1
  max_balance:      0.0
  status:           active
  gateway:          geth
  settings:
    uri:            http://10.8.0.1:8545
    secret:         'top_secret'

- name:             Ethereum Hot Wallet
  blockchain_key:   eth-rinkeby
  currency_id:      eth
  address:          '0xf2ed429fc058073e2b45af535c2c6fd7c5f14c4d'
  kind:             hot
  nsig:             1
  max_balance:      100.0
  status:           active
  gateway:          geth
  settings:
    uri:            http://10.8.0.1:8545
    secret:         'top_secret'

- name:             Trust Deposit Wallet
  blockchain_key:   eth-rinkeby
  currency_id:      trst
  address:          '0xc3f1a871ad14dcf255e27767241b869e7a878dd3'
  kind:             deposit
  nsig:             1
  max_balance:      0.0
  status:           active
  gateway:          geth
  settings:
    uri:            http://10.8.0.1:8545
    secret:         'top_secret'

- name:             Trust Hot Wallet
  blockchain_key:   eth-rinkeby
  currency_id:      trst
  address:          '0xf2ed429fc058073e2b45af535c2c6fd7c5f14c4d'
  kind:             hot
  nsig:             1
  max_balance:      100.0
  status:           active
  gateway:          geth
  settings:
    uri:            http://10.8.0.1:8545
    secret:         'top_secret'

- name:             Bitcoin Deposit Wallet
  blockchain_key:   btc-testnet
  currency_id:      btc
  address:          '2NCVY2Ad8ZgYnRAXWPxex9VcT8hAQGDatd7'
  kind:             deposit
  nsig:             1
  max_balance:      0.0
  status:           active
  gateway:          bitcoind
  settings:
    uri:            http://admin:changeme@10.8.0.1:18332

- name:             Bitcoin Hot Wallet
  blockchain_key:   btc-testnet
  currency_id:      btc
  address:          '2MuHMTcphGBH6CoRoGfi3vkTNnseNP9vrSk'
  kind:             hot
  nsig:             1
  max_balance:      100.0
  status:           active
  gateway:          bitcoind
  settings:
    uri:            http://admin:changeme@10.8.0.1:18332
